[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
tokio = { version = "1", features = ["full"] }
transports = { path = "../transports" }
bincode = "1.3"
log = "0.4"

[dev-dependencies]
env_logger = "0.9"