[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
chacha20poly1305 = "0.10"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
log = "0.4"

[dev-dependencies]
env_logger = "0.9"
