[package]
name = "transports"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
tokio = { version = "1", features = ["full"] }
log = "0.4"

[dev-dependencies]
env_logger = "0.9"